version: '3.0'

services:

  web:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  php:
    build: ./laravel/
    ports:
      - '9000:9000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./laravel:/code
      - ./laravel/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_SESSION: 1
    depends_on:
      - db
    networks:
      - app-network
    #MySQL Service
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
