version: '3.0'

services:

  web:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./laravel/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./laravel:/code
      - ./laravel/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    # depends_on:
    #   - postgres
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: accounts
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   ports:
  #     - "5432:5432"
    #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      # MYSQL_DATABASE: laravel
      # MYSQL_ROOT_PASSWORD: root
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: root
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
