version: '3.0'

services:

  web:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./app:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/code
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    # depends_on:
    #   - postgres
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: accounts
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   ports:
  #     - "5432:5432"
